In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,MaxPooling2D,Flatten

In [2]:
test_data=pd.read_csv(r'D:\Documents\PICT SEM 8\LP-5\DL\Assign3\fashion-mnist_test.csv')
train_data=pd.read_csv(r'D:\Documents\PICT SEM 8\LP-5\DL\Assign3\fashion-mnist_train.csv')
train_data.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
test_data.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train_data.isna().sum()
test_data.isna().sum()

label       0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Length: 785, dtype: int64

In [5]:
x_train_data=train_data.iloc[:,1:].values
y_train_data=train_data.iloc[:,0].values
x_test_data=test_data.iloc[:,1:].values
y_test_data=test_data.iloc[:,0].values
x_train_data=x_train_data/255.0
x_test_data=x_test_data/255.0
x_train_data=x_train_data.reshape(-1,28,28,1)
x_test_data=x_test_data.reshape(-1,28,28,1)

In [6]:
from tensorflow.keras.utils import to_categorical
y_train_data=to_categorical(y_train_data,10)
y_test_data=to_categorical(y_test_data,10)

In [7]:
model=Sequential()
model.add(Conv2D(32,(3,3),activation="relu",input_shape=(28,28,1)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64,(3,3),activation="relu",input_shape=(28,28,1)))
model.add(MaxPooling2D(2,2))

C:\Users\tanay\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [8]:
model.add(Flatten())
model.add(Dense(128,activation="relu"))
model.add(Dense(10,activation="softmax"))
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 11, 11, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 5, 5, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 1600)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         204,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 225,034 (879.04 KB)

 Trainable params: 225,034 (879.04 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.fit(x_train_data,y_train_data,epochs=10,validation_split=0.05)

Epoch 1/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 30s 16ms/step - accuracy: 0.8347 - loss: 0.4588 - val_accuracy: 0.8747 - val_loss: 0.3463
Epoch 2/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.8897 - loss: 0.3062 - val_accuracy: 0.8797 - val_loss: 0.3089
Epoch 3/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 35s 12ms/step - accuracy: 0.9026 - loss: 0.2624 - val_accuracy: 0.9010 - val_loss: 0.2737
Epoch 4/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9147 - loss: 0.2301 - val_accuracy: 0.9077 - val_loss: 0.2648
Epoch 5/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 44s 16ms/step - accuracy: 0.9255 - loss: 0.2015 - val_accuracy: 0.9000 - val_loss: 0.2750
Epoch 6/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 28s 15ms/step - accuracy: 0.9323 - loss: 0.1800 - val_accuracy: 0.9143 - val_loss: 0.2565
Epoch 7/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 37s 13ms/step - accuracy: 0.9410 - loss: 0.1604 - val_accuracy: 0.9100 - val_loss: 0.2499
Epoch 8/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 26s 15ms/step - accuracy: 0.9472 - loss: 0.1429 - val_accuracy: 0.9177 - val_loss: 0.2512
Epoch 9/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 44s 16ms/step - accuracy: 0.9524 - loss: 0.1266 - val_accuracy: 0.9020 - val_loss: 0.2996
Epoch 10/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 42s 17ms/step - accuracy: 0.9578 - loss: 0.1123 - val_accuracy: 0.9137 - val_loss: 0.2790

In [12]:
model.evaluate(x_test_data,y_test_data)
predicted=model.predict(x_test_data)
for i in range(25):
    print("Predicted Value:",predicted[i].argmax())
    print("Real Value is:",y_test_data[i])

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9199 - loss: 0.2598
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step
Predicted Value: 0
Real Value is: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 1
Real Value is: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 2
Real Value is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 6
Real Value is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 3
Real Value is: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Predicted Value: 6
Real Value is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 8
Real Value is: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Predicted Value: 4
Real Value is: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Predicted Value: 5
Real Value is: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Predicted Value: 0
Real Value is: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 3
Real Value is: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Predicted Value: 2
Real Value is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Value: 4
Real Value is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Value: 6
Real Value is: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Predicted Value: 8
Real Value is: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Predicted Value: 5
Real Value is: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Predicted Value: 6
Real Value is: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Predicted Value: 3
Real Value is: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Predicted Value: 6
Real Value is: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Predicted Value: 4
Real Value is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Value: 4
Real Value is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Value: 4
Real Value is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Value: 2
Real Value is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 1
Real Value is: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Value: 5
Real Value is: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]