In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
test_data=pd.read_csv(r'D:\Documents\PICT SEM 8\LP-5\DL\Assign3\fashion-mnist_test.csv')
train_data=pd.read_csv(r'D:\Documents\PICT SEM 8\LP-5\DL\Assign3\fashion-mnist_train.csv')
train_data.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
test_data.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train_data["label"].unique()

array([2, 9, 6, 0, 3, 4, 5, 8, 7, 1])

In [5]:
x_train=train_data.iloc[:,1:].values
y_train=train_data.iloc[:,0].values

In [6]:
x_test=test_data.iloc[:,1:].values
y_test=test_data.iloc[:,0].values

In [7]:
x_train=x_train/255.0
x_test=x_test/255.0

In [8]:
x_train=x_train.reshape(-1,28,28,1)
x_test=x_test.reshape(-1,28,28,1)

In [9]:
from tensorflow.keras.utils import to_categorical

In [10]:
y_train=to_categorical(y_train,10)
y_test=to_categorical(y_test,10)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPooling2D, Dropout
model=Sequential()
model.add(Conv2D(32,(3,3),activation="relu",input_shape=(28,28,1)))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64,(3,3),activation="relu",input_shape=(28,28,1)))
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(128,activation="relu"))
model.add(Dense(10,activation="softmax"))
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['accuracy'])

C:\Users\tanay\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 13, 13, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 11, 11, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 5, 5, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 1600)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         204,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 225,034 (879.04 KB)

 Trainable params: 225,034 (879.04 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.fit(x_train,y_train,epochs=10,validation_split=0.05)

Epoch 1/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 38s 20ms/step - accuracy: 0.8333 - loss: 0.4573 - val_accuracy: 0.8660 - val_loss: 0.3567
Epoch 2/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 40s 20ms/step - accuracy: 0.8877 - loss: 0.3073 - val_accuracy: 0.8880 - val_loss: 0.3058
Epoch 3/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 35s 16ms/step - accuracy: 0.9042 - loss: 0.2612 - val_accuracy: 0.8870 - val_loss: 0.2886
Epoch 4/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 48s 20ms/step - accuracy: 0.9156 - loss: 0.2284 - val_accuracy: 0.9023 - val_loss: 0.2598
Epoch 5/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 31s 18ms/step - accuracy: 0.9243 - loss: 0.2020 - val_accuracy: 0.8947 - val_loss: 0.2757
Epoch 6/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 35s 14ms/step - accuracy: 0.9346 - loss: 0.1777 - val_accuracy: 0.9053 - val_loss: 0.2734
Epoch 7/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9407 - loss: 0.1578 - val_accuracy: 0.9117 - val_loss: 0.2696
Epoch 8/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.9483 - loss: 0.1388 - val_accuracy: 0.9093 - val_loss: 0.2656
Epoch 9/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 36s 20ms/step - accuracy: 0.9525 - loss: 0.1250 - val_accuracy: 0.9140 - val_loss: 0.2664
Epoch 10/10
1782/1782 ━━━━━━━━━━━━━━━━━━━━ 38s 18ms/step - accuracy: 0.9595 - loss: 0.1090 - val_accuracy: 0.9120 - val_loss: 0.2935

In [17]:
predicted=model.predict(x_test)
for i in range(15):
    print("Real Category is:",y_test[i])
    print("Predicted Catefory is:",predicted[i].argmax())

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step
Real Category is: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 0
Real Category is: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 1
Real Category is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 2
Real Category is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 8
Real Category is: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 3
Real Category is: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 6
Real Category is: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Predicted Catefory is: 8
Real Category is: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Predicted Catefory is: 2
Real Category is: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Predicted Catefory is: 5
Real Category is: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 0
Real Category is: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Predicted Catefory is: 3
Real Category is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Catefory is: 2
Real Category is: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Predicted Catefory is: 4
Real Category is: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Predicted Catefory is: 6
Real Category is: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Predicted Catefory is: 8

In [18]:
output=model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9149 - loss: 0.2719

In [19]:
print("Accuracy:",output[1])

Accuracy: 0.914900004863739